# примеры API-запросов

# user1 admin Token 26944f00e3b9bef1e6b2acec08634d0b526ee28e
# user2       Token 013bde0181b311844942f95efb90b394f12ac3d0
# user3       Token 71ccf5bca2b3e3b98060e3fcf880e512ad049b2d

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 013bde0181b311844942f95efb90b394f12ac3d0

{
  "title": "Телефон12",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/6/
Content-Type: application/json
Authorization: Token 013bde0181b311844942f95efb90b394f12ac3d0

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
