# Generated by Django 5.1.7 on 2025-03-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='nullable',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
